### ISSUE TITLE
HomeBridge-http-ringer or Switch ?

### ISSUE THREAD

**Issue by TheReiner** [goedh452/homebridge-http-sprinkler#12]
Did you think it's possible to build the same plug-in with userTimer for Ringer or Switch ?
Thanks :)

**Comment by goedh452** [comment]
What do you mean bij Ringer or Switch? Are those products or do you want to toggle a switch for a specific number of minutes?

**Comment by TheReiner** [comment]
I use your plug-in with a Denkovi, and it works perfectly for my sprinkle :-) 

So, I have a doorbell button, homekit considers it as a motion sensor. Homekit refuses to use it with a Sprinkler (I connected a chime instead). If I use a Homekit switch, I can turn it off a minute later and not 2 seconds later ...

Maybe you can build the same plug-in (but for Power Point, Switch, etc...)

Sorry for my english...  
Thanks from France :)

**Comment by goedh452** [comment]
I'm afraid not. Not every homekit type accepts the use of a timer. It will always appear as a sprinkler and not as a switch.

If the sprinkler icon isn't a problem for you, then it would be possible. I coded this because I wanted to use it with a sprinkler. I'm not a very code coder, but you are welcome to clone my repository and give it a go yourself.
